name: Release Script

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'implementations/**'

jobs:
  release-code:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.repository == 'apollographql/apollo-federation-subgraph-compatibility'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Append NPM token to .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build and Test
        run: npm ci
      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
