name: AWS AppSync Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/appsync/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "appsync"
      fork: true
    secrets:
      API_KEY: ${{ secrets.API_KEY_APPSYNC }}
      TEST_URL: ${{ secrets.URL_APPSYNC }}

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
