name: StepZen Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/stepzen/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "stepzen"
      fork: true
    secrets:
      TEST_URL: ${{ secrets.URL_STEPZEN }}

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
